### ISSUE TITLE
Github action broken- Error: Version 3.5.10 with arch x64 not found during Azure Python 3.5 

### ISSUE THREAD

**Issue by Blair-Young** [noahgift/github-actions-demo#1]
When running the workflows there is a failure

eg Azure file
```
Run actions/setup-python@v1
  with:
    python-version: 3.5.10
    architecture: x64
Error: Version 3.5.10 with arch x64 not found
Available versions:

2.7.18 (x64)
3.10.2 (x64)
3.6.15 (x64)
3.7.12 (x64)
3.8.12 (x64)
3.9.10 (x64)
```

Is it a matter of converting our project to support these versions, then changing the workflow yml files to versions supported by github actions? 

Or are specific workflow files supposed to work only on certain CI platforms? 

Thanks!

**Comment by noahgift** [comment]
just upgrade to python 3.6 or higher.  at the time azure only supported 3.5

**Comment by Blair-Young** [comment]
Thanks!
